/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Casa;

/**
 *
 * @author hp
 */
public class Cardio extends javax.swing.JFrame {

    /**
     * Creates new form Cardio
     */
    public Cardio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNFUE = new javax.swing.JButton();
        btnES = new javax.swing.JButton();
        btnen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNFUE.setText("FUERZA");
        BTNFUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFUEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNFUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        btnES.setText("ESTIRAMIENTO");
        btnES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnESActionPerformed(evt);
            }
        });
        getContentPane().add(btnES, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        btnen.setText("EN CASA");
        btnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenActionPerformed(evt);
            }
        });
        getContentPane().add(btnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casa/Cardio.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenActionPerformed
       Casejer forma =new Casejer();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnenActionPerformed

    private void BTNFUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFUEActionPerformed
        Fource forma =new Fource();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNFUEActionPerformed

    private void btnESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnESActionPerformed
        Estira forma =new Estira();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNFUE;
    private javax.swing.JButton btnES;
    private javax.swing.JButton btnen;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
