/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Casa;

/**
 *
 * @author hp
 */
public class Estira extends javax.swing.JFrame {

    /** Creates new form Estira */
    public Estira() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNENC = new javax.swing.JButton();
        BTNCARD = new javax.swing.JButton();
        BTNFUER = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNENC.setText("EN CASA");
        BTNENC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNENCActionPerformed(evt);
            }
        });
        getContentPane().add(BTNENC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        BTNCARD.setText("CARDIO");
        BTNCARD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCARDActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        BTNFUER.setText("FUERZA");
        BTNFUER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFUERActionPerformed(evt);
            }
        });
        getContentPane().add(BTNFUER, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casa/Estira.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNENCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNENCActionPerformed
        Casejer forma =new Casejer();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNENCActionPerformed

    private void BTNCARDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCARDActionPerformed
        Cardio forma =new Cardio();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNCARDActionPerformed

    private void BTNFUERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFUERActionPerformed
        Fource forma =new Fource();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNFUERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCARD;
    private javax.swing.JButton BTNENC;
    private javax.swing.JButton BTNFUER;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
