/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Planes;

import login.Usuario;

/**
 *
 * @author hp
 */
public class Plapri extends javax.swing.JFrame {

    /**
     * Creates new form Plapri
     */
    public Plapri() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnaumen = new javax.swing.JButton();
        btnperder = new javax.swing.JButton();
        BTNman = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, -1, -1));

        btnaumen.setText("AUMENTAR MASA MUSCULAR");
        btnaumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaumenActionPerformed(evt);
            }
        });
        getContentPane().add(btnaumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        btnperder.setText("PERDER PESO");
        btnperder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperderActionPerformed(evt);
            }
        });
        getContentPane().add(btnperder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        BTNman.setText("MANTENERSE EN FORMA");
        BTNman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmanActionPerformed(evt);
            }
        });
        getContentPane().add(BTNman, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Planes/mage/pmasa.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 220, 230));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Planes/mage/pform.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Planes/mage/pbp.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 210, 100));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PLANES ALIMENTICIOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 340, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Planes/fp.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 773, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnperderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperderActionPerformed
        PerdeP forma=new PerdeP();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnperderActionPerformed

    private void BTNmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmanActionPerformed
         Mantener forma = new Mantener();
         forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNmanActionPerformed

    private void btnaumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaumenActionPerformed
        Masa forma=new Masa();
        forma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaumenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Usuario forma = new Usuario();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plapri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plapri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plapri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plapri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plapri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNman;
    private javax.swing.JButton btnaumen;
    private javax.swing.JButton btnperder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
