/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secciones;

import login.Usuario;

/**
 *
 * @author hp
 */
public class Cla extends javax.swing.JFrame {

    /**
     * Creates new form Cla
     */
    public Cla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnabc = new javax.swing.JButton();
        btnzumba = new javax.swing.JButton();
        btnyoga = new javax.swing.JButton();
        btnspin = new javax.swing.JButton();
        btnbc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secciones/1cc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 257, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secciones/1C_opt.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 214, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/material/abc.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 164));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secciones/y1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 184, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/material/bc_opt.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 313, 200, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CLASES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 6, 170, 46));

        btnabc.setBackground(new java.awt.Color(255, 51, 51));
        btnabc.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnabc.setText("ABDOMEN");
        btnabc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabcActionPerformed(evt);
            }
        });
        jPanel1.add(btnabc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        btnzumba.setBackground(new java.awt.Color(255, 51, 51));
        btnzumba.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnzumba.setText("ZUMBA");
        btnzumba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzumbaActionPerformed(evt);
            }
        });
        jPanel1.add(btnzumba, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        btnyoga.setBackground(new java.awt.Color(255, 51, 51));
        btnyoga.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnyoga.setText("YOGA");
        btnyoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyogaActionPerformed(evt);
            }
        });
        jPanel1.add(btnyoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 493, -1, -1));

        btnspin.setBackground(new java.awt.Color(255, 51, 51));
        btnspin.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnspin.setText("SPINNINIG");
        btnspin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspinActionPerformed(evt);
            }
        });
        jPanel1.add(btnspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 62, -1, -1));

        btnbc.setBackground(new java.awt.Color(255, 51, 51));
        btnbc.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnbc.setText("BODY COMBAT");
        btnbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbcActionPerformed(evt);
            }
        });
        jPanel1.add(btnbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 458, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jButton1.setText("REGRESAR AL MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabcActionPerformed
        Abdomen forma = new  Abdomen();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnabcActionPerformed

    private void btnzumbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzumbaActionPerformed
         VideoIntro forma = new  VideoIntro();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnzumbaActionPerformed

    private void btnspinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspinActionPerformed
        Spi forma = new  Spi();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnspinActionPerformed

    private void btnyogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyogaActionPerformed
        Yoga forma = new  Yoga();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnyogaActionPerformed

    private void btnbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbcActionPerformed
        Body forma = new  Body();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnbcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario forma = new Usuario();
        forma.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabc;
    private javax.swing.JButton btnbc;
    private javax.swing.JButton btnspin;
    private javax.swing.JButton btnyoga;
    private javax.swing.JButton btnzumba;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
